spring.application.name=task-management

spring.datasource.url=jdbc:mysql://localhost:3306/task_management

spring.datasource.username=root

spring.datasource.password=Gamalama030106.

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# tabel dibuat otomatis jika belum ada, jika sudah ada maka tidak akan diubah di database
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true